### PR TITLE
Support the new uri format for playlists

### PR DESCRIPTION
**Pull request by Peter-Lavigne**
[Spotify has two formats for playlists now.](https://developer.spotify.com/community/news/2018/06/12/changes-to-playlist-uris/) It used to be `spotify:user:spotify:playlist:37i9dQZF1DZ06evO3OC4Te`, and is now `spotify:playlist:37i9dQZF1DZ06evO3OC4Te`.

My playlists are in the new format, so I updated this to use both formats.

I don't know Scala or this tool very well so I imagine there's a cleaner solution. But it works for me and I thought I'd share instead of just making an issue 😄 

Thanks for making this tool!

### CODE REVIEW

**Comment by kubukoz** [comment]
Wow, that's interesting, I had no idea.

Looks like they rolled it back:

> Update: Due to technical issues, we have rolled back the change originally scheduled for 11th September 2018. We will communicate a new date for the change as soon as we have one.

so I assume your playlists were created while it was live? Or was it brought back?

https://developer.spotify.com/documentation/web-api/#spotify-uris-and-ids only shows the format I used here.

As for the code, I'd rather not use nulls (we could use `Option` instead). The user ID isn't really used except in the `Encoder` part of the PlaylistUri codec, but that's not in use.

Are the playlists you're talking about ones that you own, or are they built-in? You'll be able to skip and fast-forward inside playlists you don't own, but you won't be able to drop any songs, which is one of the main use cases for this app.

**Comment by kubukoz** [comment]
In any case, we can make `user` optional and skip it in the encoding - I can make that change if you want.

**Comment by Peter-Lavigne** [comment]
Some details on my playlists: I own the two I was testing this with. One is public and one is private. I made them both maybe 6-12 months ago. Not sure why they'd be using that format.

Your change looks good. Thanks!

**Comment by kubukoz** [comment]
Interesting indeed. Do you mind sharing the link to the public one with me?

I'll merge this now but I'd like to see if there's anything else we're missing.

Thanks for the idea and the initial change!

**Comment by kubukoz** [comment]
btw. I pushed a tag so 1.2.0 should be available to install via Coursier within a couple hours.

**Comment by kubukoz** [comment]
aand it's up

**Comment by Peter-Lavigne** [comment]
Sure! [Here's the link](https://open.spotify.com/playlist/5FY8ZBHJpLxWk6Zz9MX3Bw?si=3IJsUO4aQKGQBNXYYWOjYA). The URI is `spotify:playlist:5FY8ZBHJpLxWk6Zz9MX3Bw`. Thanks for getting to this so quick!

**Pull request merged**
